name: iConomy
main: com.nijiko.coelho.iConomy.iConomy
version: 5.0
authors: [ Nijikokun,Coelho,Wolfwood]
commands:
  money:
    description:  Manage your iConomy Money
    usage: /<command> [-h for more info]